# **HELLO**

In [ ]:
print("Hello World");

Hello World


In [ ]:
pip install numpy

# **IMPORT NUMPY**

In [ ]:
import numpy
arr =  numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# **Alias**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


# **Checking version**

---



In [ ]:
import numpy as np
print(np.__version__)


1.25.2


# **Data type of array**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type)

[1 2 3 4 5]
<class 'numpy.ndarray'>


# **Tupple**

In [ ]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# **0-D Arrray**

In [ ]:
arr = np.array(1)
print(arr)

1


# **1-D Array**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# **2-D Array**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# **3-D Arrays**

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,7,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 7 9]]]


# **Check number of dimensions**

In [ ]:
arr1 = np.array(1)
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,7,9]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


# **Higher Dimensional Arrays**
An array can have any number of dimensions. when the array is created, you can define the number of dimensions by usng ndmin argument


In [ ]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('Number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


# **Numpy Array Indexing**
# Acces array elements **bold text**

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])

1


# **Adding arrays**

In [ ]:
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


# **arr1= 11,12,13,14,15**
# **arr3= 16,17,18,19,20**
# **1.Print 2nd element of arr1**

In [ ]:
arr1 = np.array([11,12,13,14,15])
print(arr1[1])

12


# **2.Print 19 fromm arr3**

In [ ]:
arr3 = np.array([16,17,18,19,20])
print(arr3[3])

19


# **3.Add 3rd element of arr1 and 5th elemwent of arr3**

In [ ]:
arr1 = np.array([11,12,13,14,15])
arr3 = np.array([16,17,18,19,20])

print(arr1[2]+arr3[4])

33


# **4.Find the total of arr1 and arr3.**

In [ ]:
arr1 = np.array([11,12,13,14,15])
arr3 = np.array([16,17,18,19,20])

print(arr1+arr3)

[27 29 31 33 35]


# **Print the 2nd element on 1st row in 2D array**

In [ ]:
arr = np.ararr = np.array([[1,2,3,4],[5,6,7,8]])
print('2nd element on 1st row:',arr[0,1] )

2nd element on 1st row: 2


# **Print the 2nd element on 1st row in 3D array**

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,7,9]]])
print(arr[0,1,2])

6


# **Negative Indexing**

In [ ]:
arr = np.ararr = np.array([[1,2,3,4],[5,6,7,8]])
print('4th element on 2nd row:',arr[1,-1] )

2nd element on 1st row: 8


# **Slicing arrays**

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


# **Print all the element after 2**

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:])


[3 4 5 6 7]
[2 4 6]


# **Print each and every 2nd elemnet of the array**

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])

[2 4 6]


# **From the 2nd element slice elements from index 1 to index 4(not included)**

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2, 3])

[7 8 9]
[4]


# **from both elements, slic index 1 to index 4 (not included) this will rerturn 2-D aray:**


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# **Every other item from the entire array**

In [ ]:
arr = np.array([10,15,20,25,40,35,50])
print(arr[::2])

[10 20 40 50]


In [ ]:
arr = np.array([10,15,20,25,40,35,50])
print(arr[::3])